name: Notify Kusoblog on Slack

on:
  schedule:
    - cron: "*/5 * * * *"  # 毎5分
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: persist-credentials
      
      - name: Set up Git
        run: |
        git config user.name "github-actions[bot]"
        git config user.email "githubactions[bot]@users.noreply.github.com"
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install feedparser requests
      - name: Run script
        env:
          RSS_URL: https://mattan21.hatenablog.com/rss
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python rss_to_slack.py
      - name: Commit and push if changed
        run: |
        git add .
        git diff --cached --quiet || git commit -m "Auto update by script"
        env:
          TZ: Asia/Tokyo
      
      - name: PushChanges
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
